### ISSUE TITLE
Deleted package detected


### ISSUE THREAD

**Issue by ashishbijlani** [GlobularOne/snr#1]
I'm a Cyber Security researcher and developer of PackjGuard [1] to address open-source software supply chain attacks.

# Issue

During my research, I detected a _deleted package_ in this repository.

# Details

Specifically, the package `snr` mentioned in file `README` at line 6 does not exist on the public **PyPI** registry. A bad actor can hijack this package to propagate malicious code.

# Impact

Not only your apps/services using `https://github.com/GlobularOne/snr` repo code are vulnerable to this attack, but the users of your open-source Github repo could also fall victim.

You could read more about such attacks here: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

# Remediation
         
Please highlight this in file README and register a placeholder package for `snr` on public PyPI soon to remediate.

To automatically fix such issues in future, please install PackjGuard Github app [1].
                                         
Thanks!    

1. PackjGuard is a Github app that monitors your repos 24x7, detects vulnerable/malicious/risky open-source dependencies, and creates pull requests for auto remediation: https://github.com/marketplace/packjguard

**Comment by GlobularOne** [comment]
Thank you for the report. The given package exists on PyPI but the only available version (v0.0.1) was removed due to a bug. Making it uninstallable from PyPI. No one can inject anything as in PyPI I am the SOLE_OWNER of the snr package.

![1](https://github.com/GlobularOne/snr/assets/139503563/3f74db46-1d5d-4567-895c-a6702d0ea47e)

What this means for the users is that until a new release happens. Installation must be done from source code which I will document in the README too shortly.

**Comment by GlobularOne** [comment]
The mentioned issues were fixed in two commits:

[setup.cfg: Fixed console scripts](https://github.com/GlobularOne/snr/commit/72d8b641732beaf8a6a2f8db8b91328d9b95cc94)

[snr/main.py: Fixed the payload set update mechanism](https://github.com/GlobularOne/snr/commit/411240d4ae504704b5eaaefcbf315400ef5a94d5)

Which were done after the release (after which I removed the original tag and did another release, [leading to the PyPI upload action failing because of PyPI policy](https://github.com/GlobularOne/snr/actions/runs/8029245863)). Given how critical they were, I took the decision of removing that version from PyPI so users don't download a release that is essentially broken.
